### ISSUE TITLE
Fix formatting error

### ISSUE THREAD

**Issue by bakhshiqbal** [bakhshiqbal/collegeknight#18] opened 2018-09-27 01:59 UTC
the 'y' in privacy doesnt get underlined at the bottom of the page

**Comment by sairajaved** [comment] 2018-09-27 19:59
not a bug. The font makes it appear like that. to keep Y visible, the browser hides underline for readability, i tried it with different font and it was working perfectly fine but then the font will be inconsistent with the rest of the website. lets leave it as is for now.

**Comment by bakhshiqbal** [comment] 2018-09-28 01:40
that makes sense. i'll close the issue. @sairajaved

**Closed as completed** 2018-09-28 01:40 UTC
